### ISSUE TITLE
Issue: Language - Your Native language

### ISSUE THREAD

**Issue by KlingonMike** [MadCoder253/roll20-character-sheets#16]
There is no option for selecting your 'Native' language. You can enter a language and select the options for 'Native' but that assume that is a language you learned, not your actual 'Native' Language.
There needs to be either an option for your 'Native' language or some way to indicate it without it costing points.
Rule (23): GURPS assumes that most characters can read and write their “native” language. This ability costs no points, but you should note your native language on your character sheet; e.g., “English (Native) [0].”

Roll20: MikeW

**Comment by TankFarmer** [comment]
Maybe make it a straight input text field, no points of mods to be applied. That would be the simplest thing to do.
OR
If 2 or more Native languages are allowed, then we would have to use a repeating table for that and that is currently out of my range of capabilities -(perhaps I could learn though).

**Comment by KlingonMike** [comment]
Pull request to be made 8/01/2018 in version 1.3.7

**Comment by KlingonMike** [comment]
Pull completed 08/07/2018
