### ISSUE TITLE
[GURPS] DR Calculator

### ISSUE THREAD

**Issue by trev-dev** [MadCoder253/roll20-character-sheets#193]
This would be a feature request.

My friends and I were going over our layered armor and realized that our DR was starting to get a bit out of hand. We're having to write our DR down in our inventories, decided if we were wearing this or that piece of armor, then having to math out our DRs in various hit locations in the combat tab. It works, but it's clunky. This sheet is amazing with how it calculates most other things.

Is it possible it could do DR as well?

Ideas around how this could work from a UI perspective:

Inventory (or Combat?) tab has a new Armor table where we can add armor, row per row, and enter in the DR in one of two inline inputs. One would be for standard DR, the other for modified DR. This would help with armor that has split values for different damage types (such as flexible ballistic armor). Each row could also have an "on" checkbox, to determine if the character is wearing that piece of armor, or not.

Next, refactor the Hit Locations table to show a sum of each hit location's DR/Modified DR counts respectively. This would only require a simple arithmetic and a loop for on-change/input events in the armor rows, and would be pretty similar to the kinds of events/functions found in many other areas of the sheet.

**Comment by MadCoder253** [comment]
Thanks @trev-dev  !

**Comment by trev-dev** [comment]
No problem @MadCoder253! If I can be of further assistance let me know. I'm skilled with web development, but I don't have a pro account.

**Comment by trev-dev** [comment]
I see you, @MadCoder253. I'm looking forward to testing this out! Do you have a tip jar somewhere?

**Comment by MadCoder253** [comment]
Thanks @trev-dev ! this is the first iteration more tweaks are needed along with any ideas you may have.

**Comment by trev-dev** [comment]
Happy to share any feedback I can offer @MadCoder253 - so how about that tip jar? I can see about getting the players to buy you a coffee, too. I certainly will. While I'm reluctant to pay for "Roll20 Pro" just to contribute with code here, I don't mind offsetting your cost a little.
