### ISSUE TITLE
Attribute Check Roll Template styled incorrectly

### ISSUE THREAD

**Issue by mrianmerry** [MadCoder253/roll20-character-sheets#215]
Looks like the Roll Templates for some attribute checks are not styling correctly.

DX rolls appear to not use the colour scheme selected at all.
With the Pastel Pink style selected, it looked like all rolls weren't using the colour scheme.

**Comment by MadCoder253** [comment]
@mrianmerry this should be fixed and ready for the next update to Roll20

**Comment by imerryw1-ford** [comment]
Alrighty! I'll let you know if I see anything untoward after the next deployment.
